name: "Check PR body and files"
description: "Checks that the body or the added code contains or avoid a word, and check for number of files changed"
author: "JJ"
branding:
  icon: "git-pull-request"
  color: "gray-dark"
inputs:
  github-token:
    description: "Github token, added magically"
  additionDoesNotContain:
    description: "String that should not be in the PR body. Delimited by ;"
  linesChangedMaximum:
    description: "Max number of lines changed per PR"
  filesChangedMaximum:
    description: "Max number of files changed per PR"
outputs:
  diff:
    description: "Lines added to the PR"

runs:
  using: "node16"
  main: "dist/index.js"
